### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by Code0x58** [opsgenie/opsgenie-lamp#11]
Binary releases would be really hand for non-gophers and distribution.

An example of adding builds (using Travis) is [here](https://github.com/atombender/ktail/pull/2).

It seems there is versioning somewhere (no tags or releases here), based on this download URL from [here](https://docs.opsgenie.com/docs/lamp-command-line-interface-for-opsgenie#section-installation)→[here](https://app.opsgenie.com/download?tag=lampzip)→: https://s3-us-west-2.amazonaws.com/opsgeniedownloads/repo/opsgenie-lamp-2.6.0.zip

There's also a separate download for mac, which links to [opsgenie-integration](https://github.com/opsgenie/opsgenie-integration/).

**Comment by primeroz** [comment]
https://app.opsgenie.com/download?tag=lampzip 

Should always redirect ot the latest version on the amazonaws link

**Comment by jimsheldon** [comment]
If not binary releases, could there at least be version tags in this repo?

**Comment by tobzsc** [comment]
Version tags would be very very nice!
