### ISSUE TITLE
Cannot go get opsgenie-lamp due to bad github.com/codegangsta/cli import

### ISSUE THREAD

**Issue by ghost** [opsgenie/opsgenie-lamp#14]
`github.com/codegangsta/cli` recently was renamed `github.com/urfave/cli` and as such `go get opsgenie-lamp` reports an error parsing `go.mod`.

```
go: github.com/opsgenie/opsgenie-lamp imports
	github.com/codegangsta/cli: github.com/codegangsta/cli@v1.21.0: parsing go.mod: unexpected module path "github.com/urfave/cli"
```

Fix is to change `lamp.go` and other files that import the renamed repo.

**Comment by ErenKizilay** [comment]
https://github.com/opsgenie/opsgenie-lamp/commit/bc1fc12dfc4d5488988a31c98ee4413510291827 this one should resolve the problem. thanks for the report.

**Comment by ghost** [comment]
Verified this fixed the issue on our end. Thank you!
