### ISSUE TITLE
Provide Changelog

### ISSUE THREAD

**Issue by francogu** [opsgenie/opsgenie-lamp#24]
Hello, 

Could you please provide a changelog for this tool ?

We are using the version 2.6 and we discovered that he version is now 3.2 but there is explantion about the changes either here or at https://docs.opsgenie.com/docs/lamp-command-line-interface-for-opsgenie

Best Regards.

**Comment by prakhar-mudaiya** [comment]
Added CHANGELOG.md in latest release (v3.1.4)
