### ISSUE TITLE
Use of tags

### ISSUE THREAD

**Issue by francogu** [opsgenie/opsgenie-lamp#25]
Hello,

We are using the binary version 2.6 and discovered that there a version binaries version 3.2

We wanted to check to difference between both versions. However, only tag for version 3.1.1 and 3.1.2 are available preventing to get the changes.

Could you please put the corresponding tag or at least ensure tag are available for next version ?

Best Regards.

**Comment by prakhar-mudaiya** [comment]
Sure @francogu , we have now moved to github actions for release. So, all the binaries will be available in github itself and we will make sure all release have a tag associated with it. Sorry for the issue.
